"""add_placement_events_and_audits

Revision ID: 112187d9593e
Revises: 25a257f2639e
Create Date: 2026-06-18 02:06:36.686041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112187d9593e'
down_revision: Union[str, Sequence[str], None] = '25a257f2639e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('placement_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_session_id', sa.String(), nullable=False),
    sa.Column('checkpoint', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['placement_session_id'], ['placement_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_audits_session_checkpoint', 'placement_audits', ['placement_session_id', 'checkpoint'], unique=True)
    op.create_table('placement_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('target_event_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['placement_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_events_idempotency', 'placement_events', ['idempotency_key'], unique=True)
    op.create_index('ix_placement_events_session_pos', 'placement_events', ['session_id', 'position'], unique=False)
    op.create_table('placement_audit_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_audit_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('sample_batch', sa.Integer(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('correct_option_id', sa.String(), nullable=False),
    sa.Column('resolved_result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['placement_audit_id'], ['placement_audits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_audit_items_audit_batch', 'placement_audit_items', ['placement_audit_id', 'sample_batch'], unique=False)
    op.create_table('placement_audit_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_audit_item_id', sa.String(), nullable=False),
    sa.Column('selected_option_id', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['placement_audit_item_id'], ['placement_audit_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_placement_audit_events_idempotency', 'placement_audit_events', ['idempotency_key'], unique=True)
    op.add_column('placement_items', sa.Column('undone', sa.Boolean(), nullable=True))
    op.add_column('placement_items', sa.Column('audit_reclassified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_placement_items_audit_reclassified'), 'placement_items', ['audit_reclassified'], unique=False)
    op.create_index(op.f('ix_placement_items_undone'), 'placement_items', ['undone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_placement_items_undone'), table_name='placement_items')
    op.drop_index(op.f('ix_placement_items_audit_reclassified'), table_name='placement_items')
    op.drop_column('placement_items', 'audit_reclassified')
    op.drop_column('placement_items', 'undone')
    op.drop_index('ix_placement_audit_events_idempotency', table_name='placement_audit_events')
    op.drop_table('placement_audit_events')
    op.drop_index('ix_placement_audit_items_audit_batch', table_name='placement_audit_items')
    op.drop_table('placement_audit_items')
    op.drop_index('ix_placement_events_session_pos', table_name='placement_events')
    op.drop_index('ix_placement_events_idempotency', table_name='placement_events')
    op.drop_table('placement_events')
    op.drop_index('ix_placement_audits_session_checkpoint', table_name='placement_audits')
    op.drop_table('placement_audits')
    # ### end Alembic commands ###
