"""add_study_eligible_data_quality_status

Revision ID: 25a257f2639e
Revises: b74c13e326c1
Create Date: 2026-06-18 01:44:53.394018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a257f2639e'
down_revision: Union[str, Sequence[str], None] = 'b74c13e326c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('study_eligible', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('data_quality_status', sa.String(), nullable=True))
    op.execute("UPDATE cards SET study_eligible = 1 WHERE study_eligible IS NULL")
    op.execute("UPDATE cards SET data_quality_status = 'clean' WHERE data_quality_status IS NULL")
    op.create_index(op.f('ix_cards_data_quality_status'), 'cards', ['data_quality_status'], unique=False)
    op.create_index(op.f('ix_cards_study_eligible'), 'cards', ['study_eligible'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_study_eligible'), table_name='cards')
    op.drop_index(op.f('ix_cards_data_quality_status'), table_name='cards')
    op.drop_column('cards', 'data_quality_status')
    op.drop_column('cards', 'study_eligible')
    # ### end Alembic commands ###
