"""Add problematic_reason

Revision ID: 3a40a062de75
Revises: d2985c3dd4dc
Create Date: 2026-06-18 00:31:56.488770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a40a062de75'
down_revision: Union[str, Sequence[str], None] = 'd2985c3dd4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_items', sa.Column('problematic_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placement_items', 'problematic_reason')
    # ### end Alembic commands ###
