"""Initial schema

Revision ID: b854534bf263
Revises: 
Create Date: 2026-06-18 00:29:47.388245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b854534bf263'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('english', sa.String(), nullable=False),
    sa.Column('english_normalized', sa.String(), nullable=False),
    sa.Column('chinese_meaning', sa.String(), nullable=False),
    sa.Column('chinese_normalized', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('sense_hint', sa.String(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_active'), 'cards', ['active'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('placement_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('manifest_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requested_size', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('cards_answered', sa.Integer(), nullable=True),
    sa.Column('again_count', sa.Integer(), nullable=True),
    sa.Column('hard_count', sa.Integer(), nullable=True),
    sa.Column('good_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('confusion_counts',
    sa.Column('target_card_id', sa.String(), nullable=False),
    sa.Column('selected_wrong_card_id', sa.String(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=True),
    sa.Column('last_occurred_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['selected_wrong_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['target_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('target_card_id', 'selected_wrong_card_id')
    )
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('source_import_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_id')
    )
    op.create_table('placement_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('placement_session_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('placement_result', sa.String(), nullable=True),
    sa.Column('was_audited', sa.Boolean(), nullable=True),
    sa.Column('audit_correct', sa.Boolean(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['placement_session_id'], ['placement_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_placement_items_session_position', 'placement_items', ['placement_session_id', 'position'], unique=False)
    op.create_table('review_states',
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('due', sa.DateTime(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('scheduler_name', sa.String(), nullable=True),
    sa.Column('scheduler_version', sa.String(), nullable=True),
    sa.Column('parameters_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_review_states_due'), 'review_states', ['due'], unique=False)
    op.create_table('session_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_card_id', sa.String(), nullable=False),
    sa.Column('correct_option_card_id', sa.String(), nullable=False),
    sa.Column('option_card_ids_json', sa.JSON(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.ForeignKeyConstraint(['target_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('activation_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('source_placement_item_id', sa.String(), nullable=True),
    sa.Column('activation_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['source_placement_item_id'], ['placement_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('study_session_id', sa.String(), nullable=True),
    sa.Column('session_item_id', sa.String(), nullable=True),
    sa.Column('selected_option_card_id', sa.String(), nullable=True),
    sa.Column('correct_option_card_id', sa.String(), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('previous_state_json', sa.JSON(), nullable=True),
    sa.Column('next_state_json', sa.JSON(), nullable=True),
    sa.Column('previous_due', sa.DateTime(), nullable=True),
    sa.Column('next_due', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['session_item_id'], ['session_items.id'], ),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_review_logs_reviewed_at'), 'review_logs', ['reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_reviewed_at'), table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_table('activation_queue')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_review_states_due'), table_name='review_states')
    op.drop_table('review_states')
    op.drop_index('ix_placement_items_session_position', table_name='placement_items')
    op.drop_table('placement_items')
    op.drop_table('deck_cards')
    op.drop_table('confusion_counts')
    op.drop_table('study_sessions')
    op.drop_table('placement_sessions')
    op.drop_table('decks')
    op.drop_index(op.f('ix_cards_active'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
