"""add_import_schema

Revision ID: bbe1772720c8
Revises: 3a40a062de75
Create Date: 2026-06-18 01:07:52.785240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe1772720c8'
down_revision: Union[str, Sequence[str], None] = '3a40a062de75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('detected_encoding', sa.String(), nullable=False),
    sa.Column('field_mapping_json', sa.JSON(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('valid_rows', sa.Integer(), nullable=True),
    sa.Column('invalid_rows', sa.Integer(), nullable=True),
    sa.Column('new_cards', sa.Integer(), nullable=True),
    sa.Column('linked_existing_cards', sa.Integer(), nullable=True),
    sa.Column('skipped_duplicates', sa.Integer(), nullable=True),
    sa.Column('conflict_count', sa.Integer(), nullable=True),
    sa.Column('deck_selection', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('request_hash', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_idempotency', 'import_jobs', ['idempotency_key'], unique=True)
    op.create_table('import_row_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('import_job_id', sa.String(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('original_row_data', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('card_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cards', sa.Column('fingerprint', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('fingerprint_version', sa.Integer(), nullable=True))
    op.execute(
        """
        UPDATE cards
        SET fingerprint = lower(hex(randomblob(16))),
            fingerprint_version = 0
        WHERE fingerprint IS NULL
        """
    )
    op.create_index(op.f('ix_cards_fingerprint'), 'cards', ['fingerprint'], unique=False)
    op.add_column('decks', sa.Column('deck_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'deck_type')
    op.drop_index(op.f('ix_cards_fingerprint'), table_name='cards')
    op.drop_column('cards', 'fingerprint_version')
    op.drop_column('cards', 'fingerprint')
    op.drop_table('import_row_results')
    op.drop_index('ix_import_jobs_idempotency', table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
