"""Add manifest_json

Revision ID: d2985c3dd4dc
Revises: b854534bf263
Create Date: 2026-06-18 00:30:23.455466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2985c3dd4dc'
down_revision: Union[str, Sequence[str], None] = 'b854534bf263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('placement_sessions', sa.Column('manifest_json', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('placement_sessions', 'manifest_json')
    # ### end Alembic commands ###
